### ISSUE TITLE
Options should be separeted into global options, infile options and outfile options.

### ISSUE THREAD

**Issue by mizzy** [mizzy/FFmpeg-Command#3]
I opened this issue for the discussion in #1.

**Comment by mizzy** [comment]
@c0decafe, @sumikawa

I'm trying to fix this issue in separate-options branch.
https://github.com/mizzy/FFmpeg-Command/tree/separate-options

I would appreciate if you try this version and give me some feedback.

**Comment by mizzy** [comment]
Hmm, this implementation is not so good.

In man of ffmpeg command, options are described like this:

```
ffmpeg [global options] [[infile options][-i infile]]... {[outfile options] outfile}...
```

So "infile options -i infile" could be appear several times.My implementation
doesn't meet this rule.

**Comment by SteveBz** [comment]
I agree with the three types of options (global options, infile options and outfile options), but the problem is that it will not be backward compatible.  This needs some thought.

In reality all options used to be treated as outfile options, so you could have _four_ sets of options:
global options, infile options (goes before -i) and outfile options and options (this is the OLD options) goes before -o.  That way it would be backwards compatible as long as it dealt with undefined global options, infile options and outfile options.  Of course it might not work because Ffmpeg has changed but that would not be Command.pm's fault.

ffmpeg [global_options] [[infile_options][-i infile]]... {[outfile_options] [options] outfile}...

Regards

Steve

**Comment by SteveBz** [comment]
One more thought, could it detect what version  of ffmpeg is being used and give an error or the wrong option set is being used?  Either:

ffmpeg [-i infile]]... {[options] outfile}...

_or_

ffmpeg [global_options] [[infile_options][-i infile]]... {[outfile_options] outfile}...

Regards

Steve

**Comment by sumikawa** [comment]
How about supporting the below four patterns?

*Pattern A

global_options: '-ga -gb'
infile_options: '-ia -ib'
outfile_options: '-oa -ob'
input_file: 'filename1'
output_file: 'output_file'
options: ''

=> 'ffmpeg -ga -gb -ia -ib -i filename1 -oa -ob output_file'

*Pattern B

global_options: ''
infile_options: ''
outfile_options: ''
input_file: 'filename1'
output_file: 'output_file'
options: '-ga -gb -ia -ib -oa -ob'

=> 'ffmpeg -i filename1 -ga -gb -ia -ib -oa -ob output_file'

*Pattern C

global_options: '-ga -gb'
infile_options: '-ia -ib'
outfile_options: '-oa -ob'
input_file: ['filename1', 'filename2']
output_file: 'output_file'
options: ''

=> 'ffmpeg -ga -gb -ia -ib -i filename1 -ia -ib -i filename2 -oa -ob output_file'

*Pattern D

global_options: ''
infile_options: ''
outfile_options: ''
input_file: ''
output_file: 'output_file'
options: '-ga -gb -ia1 -ib1 -i filename1 -ia2 -ib2 -i filename2 -oa -ob'

=> 'ffmpeg -ga -gb -ia1 -ib1 -i filename1 -ia2 -ib2 -i filename2 -oa -ob output_file'

My points are;
- Pattern A is new default case
- Pattern B is for backward compatibility and/or easily understanding for newbies of ffmpeg who doesn't know the crazy options system.  This is not correct usage but it works in many casual cases as we know
- Pattern C uses the replicated infile_options for every input file
- Pattern D should be really special case.  In this case, programmers want to use different infile options for each input file and they need to write down almost everything on the 'options' (let's say raw mode)

**Comment by SteveBz** [comment]
Hi Guys,

Firstly I'd like to apologise that I cannot reply in Japanese and to thank you for your excellent English.

Secondly, Sumikawa, I think its a great idea and this post should be added pretty much unchanged to the documentation.  I love option 4 especially.

Can you do it Mizzy?

Regards

Steve

**Comment by mizzy** [comment]
Hi everyone,

Thanks for your idea, Sumikawa-san.These are very helpful for me
to simplify this issue.

Steve, do you mean that "option 4" is same as "Pattern D" of Sumikawa's idea?
You can use this pattern with the current version of FFmpeg::Command.

For easy testing that options are correct, I fixed this module and add a test.
Please check it.

https://github.com/mizzy/FFmpeg-Command/tree/fix-handling-options

If the pattern D is acceptable, I will not change this module anymore.
(But I will fix the pod a little.)

**Comment by SteveBz** [comment]
Hi Mizzy,

Sorry, yes I did mean that, I just wasn't being clear.  I meant Pattern D.

And it's true, you can use it now.  I should have done that instead of all the hacking I did do :(

However, while I understand maybe you don't need to do all the changes suggested here, I feel we should at least have the global options parameter.

The problem with [infile options] and [outfile options] is that it leads to Pattern C, which is a little strange and means you fall back to the old (raw) options style.  At least the [global options] idea is forward looking and allows you to put options _before_ the -i option.

My vote would be to add the [global options] parameter alone.  Wait and see how it is received and then maybe think about [infile options] and [outfile options].

I hope that helps.

Regards

Steve

**Comment by SteveBz** [comment]
-**PACKAGE**->mk_accessors( qw( input_file output_file ffmpeg options timeout stdin stdout stderr command ) );
+**PACKAGE**->mk_accessors( qw( input_file output_file ffmpeg options global-options timeout stdin stdout stderr command ) );

Is very simple and poses no danger to existing users.

+global-options     => [],                             # After timeout parameter, to avoid disrupting existing applications

+@{ $self->global-options },                        # After '-y', line and before map ( { ( '-i', $_ ) } @$files ), line

I would hope this is then free of side-effects to existing users, but provides some forward-looking direction for new users.  Otherwise, the danger is it becomes harder to use for new users.

What do you feel about all this?

Thanks for all your time and effort.

Regards

Steve

**Comment by sumikawa** [comment]
To avoid to mis-understanding what I say, I will write this post both in English and Japanese

Mizzyさん、念のため書きますが、僕の提案はパターンA〜Dを全部サポートして、どの場合でも動くようにすることです。どれか一つではないです。

すなわち、ブランチseparate-optionsの修正にプラスして、infile_optionsを-iごとに複製する修正をいれれば、提案相当になるかと思います。いかがでしょう。

Mizzy-san, you may be misunderstanding my idea due to my poor explanation. My proposal is FFmpeg::Command supports _all of_ patterns A/B/C/D.  This is not choice.  That's is the reason why I use 'pattern'
instead of 'option'.  FFmpeg::Commands can be modified to work in any cases.

Implemntation point of view, if we just add "replicating infile_options for each '-i'" on the brach 'sepatate-options', it should be my proposal.

**Comment by mizzy** [comment]
Sumikaw-san, you're right.I've misunderstood your proposal.
Sorry and thanks for your pointing.

Now I understand your proposal and I will implement your proposal
on fix-handling-options branch.

Patches are welcome :)

**Comment by SteveBz** [comment]
I'm sorry I didn't use svn to implement this, I used cpan.

Is there some way to use cpan to produce a patch?

Regards

Steve

**Comment by mizzy** [comment]
@SteveBz , please send me your patches as pull requests.(That is one of GitHub's features.)
http://help.github.com/send-pull-requests/

**Comment by mizzy** [comment]
@SteveBz If you send me your patches through pull requests,
patches based on fix-handling-options would be appreciate.

**Comment by sumikawa** [comment]
> Patches are welcome :)

Sure.  Please review my proposal.
https://github.com/mizzy/FFmpeg-Command/pull/5

**Comment by mizzy** [comment]
@sumikawa san, thanks for your great patch.
I've merged it just now.

I will add some other tests and rewrite pod.

**Comment by sumikawa** [comment]
Steve,

> My vote would be to add the [global options] parameter alone. Wait and see how it is received and then maybe think about [infile options] and [outfile options].

The original motivation of splitting [options] was from https://github.com/mizzy/FFmpeg-Command/pull/1
It seems that c0deface already requires [infile options].

**Comment by mizzy** [comment]
HI guys,

I've add a test, fix pod and edit Changes.

https://github.com/mizzy/FFmpeg-Command/compare/07d29f4835...c9e4793c95

@sumikawa , @SteveBz , could you check this fix-handling-options version, please?

If there are no problems, I will merge it to master and release it to CPAN.

Thanks.

**Comment by mizzy** [comment]
@sumikawa  san, I added your name in AUTHORS of the pod.

Is it OK?If you don't like this, please tell me.

**Comment by SteveBz** [comment]
Guys,

You are wonderful.  I'm sorry I didn't contribute.  

I'll check out the code and test it in the coming week.

If I have any comments I'll contribute them via Github.  I'm very impressed by it.

Regards.

**Comment by sumikawa** [comment]
Yes, It's okay to add my name on the AUTHORS.
Thanks for the caring that.

**Comment by SteveBz** [comment]
_Thanks for the caring_
I agree.  Mizzy gets my vote too.  I think he's going to be a great Dad!

**Comment by sumikawa** [comment]
> @sumikawa , @SteveBz , could you check this fix-handling-options version, please?

I've checked it.  Seems fine!

**Comment by mizzy** [comment]
@sumikawa san, thanks for your checking.
I've uploaded to CPAN as 0.18 just now.

@SteveBz , I also appreciate you.Thanks for your comments
and trying to send me patches.

Now I'm closing this issue.If you find any problems, please
let me known.

Thanks a lot.

**Comment by SteveBz** [comment]
Hi Guys,

I'm thinking now we should have had this conversation on
ffmpeg-user@ffmpeg.org, which is the support group for ffmpeg.  It gets
10-20 messages per day and obviously more who just read the group.  That way
it would have publicised Ffmpeg::Command and perhaps encouraged new users.

What do you think?

Regards

Steve

-----Original Message-----
From: Munechika Sumikawa
[mailto:reply+i-4121783-0dc313157083e33398a9ab66ce4931ba50b62e7a-1646078@rep
ly.github.com] 
Sent: 17 April 2012 12:46
To: SteveBz
Subject: Re: [FFmpeg-Command] Options should be separeted into global
options, infile options and outfile options. (#3)

Yes, It's okay to add my name on the AUTHORS.
Thanks for the caring that.

---
